"""Add photo to cars

Revision ID: c7e63ec87fd9
Revises: 601203f15587
Create Date: 2021-06-08 08:00:27.972811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e63ec87fd9'
down_revision = '601203f15587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('photo_filename', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'photo_filename')
    # ### end Alembic commands ###
